# seed
seed: 4641

# hyperparameters
train_episodes: 2000
gamma: 0.99
lr: 3e-4
tau: 0.005
batch_size: 256
buffer_size: 1e6

defaults:
    - _self_
    #- agent: ddpg
    - override hydra/hydra_logging: disabled  
    - override hydra/job_logging: disabled 

# define task
agent_name: ddpg   
env_name: bipedalwalker_easy

# define experiment info
exp_name: ddpg_bipedalwalker
run_id: ??? # decided during execution

testing: false
model_path: default

save_video: false
save_logging: false
save_model: true
use_wandb: true
silent: false

run_suffix: 0
# ref: https://stackoverflow.com/questions/65104134/disable-file-output-of-hydra
hydra:  
    output_subdir: null  
    run:  
        dir: .

